### ISSUE TITLE
Unsurprising controller findings.

### ISSUE THREAD

**Issue by Aciid** [MAVProxyUser/P0VsRedHerring#10]
Decided to connect the controller to the workstation, turns out it's running the same set of software.
This might be old news, but I recon that the same workaround should work here as well, I read througly through fireworks, but I'm not ready to kick that in without having seen the controller dumps yet to match the commands. 

It would be a shame if my fridge has more twitter followers than my RC controller.
Controller micro-USB to workstation and FTP in 192.168.42.2 is writable just as it is in the mavic /upgrade path.

[Port 6] USB Composite Device
      Remote NDIS based Internet Sharing Device #2
      USB Mass Storage Device
      DJI File-CD Gadget USB Device
      Vision (Interface 3)
      USB Serial Device (COM4)

**Comment by Aciid** [comment]
Ah this seems to be a duplicate of #8, sorry for bringing this up again.

**Comment by MAVProxyUser** [comment]
Unless someone wants to send a PR... this is unlikely to get fixed in the near term... please migrate to PyDUML by @hdnes https://github.com/hdnes/pyduml/blob/master/pyduml.py
