### ISSUE TITLE
Impressive 👏

### ISSUE THREAD

**Issue by peeohvee** [MAVProxyUser/P0VsRedHerring#3]
Check the update: https://www.rcgroups.com/forums/showpost.php?p=36232471&postcount=15113

Apologies for the spam. I didn't want to dig around to find the best way to contact. This can be closed.

**Comment by MAVProxyUser** [comment]
+100 Thanks stranger !

**Comment by MAVProxyUser** [comment]
If you care to share more on the mythical Whitelist... by all means leave another trail of bits, or reach out directly. 

Thank you kindly for what you did share.
