### ISSUE TITLE
image.py

### ISSUE THREAD

**Issue by rulppa** [MAVProxyUser/P0VsRedHerring#4]
anyone here with osx and able to actually run the image.py 

sh-3.2# python3 image.py wm620_1203_v01.02.00.46_20160918.pro.fw.sig 
Traceback (most recent call last):
  File "image.py", line 27, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

I have the crypto installed, uninstalled and installed again, same error. Before that, i got some other error and installed needed things for that, but now i'm kinda stuck here.

**Comment by MAVProxyUser** [comment]
Try:

sudo pip3 install pycrypto
or
easy_install pycrypto
^--- yes using easy_install can make a difference.

**Comment by rulppa** [comment]
Requirement already satisfied: pycrypto in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages

not that.

**Comment by MAVProxyUser** [comment]
Trust me... uninstall and reinstall using easy_install.

**Comment by rulppa** [comment]
I've done it 2-3times before I made the issue, doesn't help.

**Comment by fvantienen** [comment]
I don't know why.. I have installed it successfully on my mac and am able to run it.

**Comment by MAVProxyUser** [comment]
What is your Python module path variable set to? Also are you typing. Where is your Python 3 from? Brew?

**Comment by MAVProxyUser** [comment]
You can also use "binwalk -e" to extract technically...
https://github.com/devttys0/binwalk

**Comment by MAVProxyUser** [comment]
you must not have both Crypto and pycrypto 
remove both and install pycrypto only
https://stackoverflow.com/questions/31485110/no-module-named-crypto-cipher

via kilrah on Slack. "that's the problem, you must only have one insalled, NOT both"
