### ISSUE TITLE
Broken audio in VirtualBox OSX hangs ruby script

### ISSUE THREAD

**Issue by HFMan** [MAVProxyUser/P0VsRedHerring#7]
I have VirtualBox running OSX El Capitan on a Windows 10 host.  Audio is configured in VirtualBox, but clearly this VM doesn't appear to support sound at all.  When the 'say' function is called, the script just hangs.  I had to comment out all of the 'say' functions to get it to proceed.  I don't know if this an error condition that might be able to be trapped, as it does just seem to hang.

**Comment by MAVProxyUser** [comment]
all audio calls have been removed... they were too much anyway...
