### ISSUE TITLE
not working with Mavic RC

### ISSUE THREAD

**Issue by Mavic129** [MAVProxyUser/P0VsRedHerring#8]
Mavic RC doesn't have NFZ update only regular upgrade/downgrade

**Comment by MAVProxyUser** [comment]
This should be a good start to getting this to work.. 

@hotelzululima has also requested it. 

https://github.com/MAVProxyUser/P0VsRedHerring/commit/808d47ae72e181db3cd68a7fae9a83d58cfa5adb

**Comment by MAVProxyUser** [comment]
You'll have to update us with your variant @Mavic129 congrats on the root shell tonight. Excellent job.

**Comment by MAVProxyUser** [comment]
Unless someone wants to send a PR... this is unlikely to get fixed in the near term... please migrate to PyDUML by @hdnes https://github.com/hdnes/pyduml/blob/master/pyduml.py
