### ISSUE TITLE
What does this undefined error mean?

### ISSUE THREAD

**Issue by BeeCodiing** [MAVProxyUser/P0VsRedHerring#9]
I'm getting this error when I try to update the NFZs: `undefined 0x0a00ce`. What does it mean??
My current setup is: my laptop (linux) running the web server in ruby and my windows PC with the hosts modified to redirect to the "fake server". I need some help plz!

**Comment by MAVProxyUser** [comment]
which git commit are you working from? 
What command line are you using? 
What drone are you attacking?

**Comment by BeeCodiing** [comment]
Sorry that I didn't provide that info. I was going to sleep and totally forgot that...
The commit that I'm working from is the lastest one from now (ba2144cf698e848a5167af7860dc217a15e94ba0) in the master branch
The command that I'm using is `sudo ./RedHerring.rb /system/bin/start_dji_system.sh system/bin/start_dji_system.sh`
And I'm attacking the Mavic Pro

**Comment by MAVProxyUser** [comment]
Ahh yeah that is gonna be the issue. Mavic has a "ro" /system folder. 
See here for full details: 
https://github.com/MAVProxyUser/P0VsRedHerring/issues/5

Short answer: "sudo ./RedHerring.rb /data/.bin/grep grep" the "grep" file is included in the repo https://github.com/MAVProxyUser/P0VsRedHerring/blob/master/grep
